service: ocorrencia-service
frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  environment:
    ORACLE_USER: ${env:ORACLE_USER}
    ORACLE_PASSWORD: ${env:ORACLE_PASSWORD}
    ORACLE_DSN: ${env:ORACLE_DSN}

functions:
  createOcorrencia:
    handler: ocorrencia/handler/create.handler
    events:
      - httpApi:
          path: /ocorrencia
          method: post

  listOcorrencias:
    handler: ocorrencia/handler/list.handler
    events:
      - httpApi:
          path: /ocorrencia
          method: get

  updateOcorrencia:
    handler: ocorrencia/handler/update.handler
    events:
      - httpApi:
          path: /ocorrencia/{id}
          method: put

  deleteOcorrencia:
    handler: ocorrencia/handler/delete.handler
    events:
      - httpApi:
          path: /ocorrencia/{id}
          method: delete
  

  createFuncionario:
    handler: funcionario/handler/create.handler
    events:
      - httpApi:
          path: /funcionario
          method: post


  listFuncionario:
    handler: funcionario/handler/list.handler
    events:
      - httpApi:
          path: /funcionario
          method: get

  updateFuncionario:
    handler: funcionario/handler/update.handler
    events:
      - httpApi:
          path: /funcionario/{id}
          method: put

  deleteFuncionario:
    handler: funcionario/handler/delete.handler
    events:
      - httpApi:
          path: /funcionario/{id}
          method: delete

  getFuncionario:
    handler: funcionario/handler/get.handler
    events:
      - httpApi:
          path: /funcionario/{id}
          method: get
  
  createAtendimento:
    handler: atendimento/handler/create.handler
    events
      - httpApi:
          path: atendimento
          method: put
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true # usa container AL2 + Python3.9
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-x86_64
    dockerPlatform: linux/amd64
    slim: true
    strip: true
    useDownloadCache: false
    useStaticCache: false
    pythonBin: python3.9
    noDeploy:
      - boto3
      - botocore
